### ISSUE TITLE
Screenshots for ReadMe

### ISSUE THREAD

**Issue by ssibbett** [EsriCanada/ParcelFabricSmoothRadius#1]
![add-intointerface](https://cloud.githubusercontent.com/assets/8808482/16597948/8dc5356a-42c9-11e6-83cb-8f4723466e71.jpg)
![snaptopoint](https://cloud.githubusercontent.com/assets/8808482/16598126/6ea32a38-42ca-11e6-81f8-48169a1968c8.jpg)
![smoothradiuswindow](https://cloud.githubusercontent.com/assets/8808482/16598130/71c85dc8-42ca-11e6-846d-3eac0c5a540f.jpg)
![options](https://cloud.githubusercontent.com/assets/8808482/16598135/74e2914a-42ca-11e6-9c71-3809f2200668.jpg)

**Comment by travisval** [comment]
Not actually an issue, closed.
