### ISSUE TITLE
Updated Screenshots for ReadMe

### ISSUE THREAD

**Issue by ssibbett** [EsriCanada/ParcelFabricSmoothRadius#2]
![addtointerface](https://cloud.githubusercontent.com/assets/8808482/16619380/d553401a-435b-11e6-91ed-10021bd8a612.jpg)
![options](https://cloud.githubusercontent.com/assets/8808482/16619382/d6c2c6e6-435b-11e6-8914-d755bc95aac8.jpg)
![snappoint](https://cloud.githubusercontent.com/assets/8808482/16619384/daaa7308-435b-11e6-9823-ed49174653ab.jpg)
![window](https://cloud.githubusercontent.com/assets/8808482/16619388/dce66cf8-435b-11e6-89fe-722c3ada5894.jpg)

**Comment by travisval** [comment]
Not actually an issue, so closed.
